#' Print formatted tldr response
#'
#' @param response The raw response from the AI
#' @param func_name The name of the function
#' @param verbose Whether verbose output was requested
#' @param examples Number of examples requested
#'
#' @return Invisibly returns NULL
#' @keywords internal
print_tldr_response <- function(response, func_name, verbose, examples) {
  # Extract the code block content
  content <- extract_code_block(response)
  
  # Use cli to format the output nicely
  cat("\n")
  cli::cli_h1(paste0("tldrAI: ", func_name))
  
  # Print the content
  cat(format_content(content))
  
  # Add a footer
  cat("\n")
  cli::cli_text("{.emph Generated by tldrAI using Claude's API}")
  cat("\n")
  
  invisible(NULL)
}

#' Extract the content from code blocks in the response
#'
#' @param response The raw response from the AI
#'
#' @return Character string with the content from the code block
#' @keywords internal
extract_code_block <- function(response) {
  # Extract text between triple backticks
  pattern <- "```(.*?)```"
  matches <- regmatches(response, gregexpr(pattern, response, dotall = TRUE))[[1]]
  
  if (length(matches) == 0) {
    # If no code blocks found, return the whole response
    return(response)
  }
  
  # Remove the backticks and any language specification
  content <- gsub("```[rR]?\\s*|```", "", matches[1])
  
  content
}

#' Format the content for display
#'
#' @param content The content to format
#'
#' @return Character string with the formatted content
#' @keywords internal
format_content <- function(content) {
  # Split the content by lines
  lines <- strsplit(content, "\n")[[1]]
  
  # Process each line
  formatted_lines <- character(length(lines))
  in_r_code_block <- FALSE
  
  for (i in seq_along(lines)) {
    line <- lines[i]
    
    # Check for section headers (## Title)
    if (grepl("^##\\s+", line)) {
      formatted_lines[i] <- cli::col_cyan(line)
    } 
    # Check for code blocks (```r)
    else if (grepl("^```r", line)) {
      in_r_code_block <- TRUE
      formatted_lines[i] <- ""
    }
    # Check for end of code blocks (```)
    else if (grepl("^```$", line)) {
      in_r_code_block <- FALSE
      formatted_lines[i] <- ""
    }
    # Format code differently
    else if (in_r_code_block) {
      formatted_lines[i] <- cli::col_yellow(line)
    }
    # Check for bullet points
    else if (grepl("^-\\s+", line)) {
      # Extract the bullet point text
      bullet_text <- gsub("^-\\s+", "", line)
      # Split by colon if present
      if (grepl(":", bullet_text)) {
        parts <- strsplit(bullet_text, ":\\s*", 2)[[1]]
        formatted_lines[i] <- paste0("- ", cli::col_green(parts[1]), ": ", parts[2])
      } else {
        formatted_lines[i] <- paste0("- ", bullet_text)
      }
    }
    # Regular text
    else {
      formatted_lines[i] <- line
    }
  }
  
  # Join the lines back together
  paste(formatted_lines, collapse = "\n")
}